# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectSetup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ProjectSetup
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire', '~> 4.8'
  pod 'Reachability'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Crashlytics'
  
end
