# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project Setup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project Setup
  pod 'SVProgressHUD', '~> 2.2'
  pod 'IQKeyboardManagerSwift', '~> 6.2'
  pod 'Reachability'
  pod 'Alamofire'
  pod 'Fabric', '~> 1.9'
  pod 'Crashlytics', '~> 3.12'
  
end
